### ISSUE TITLE
guest checkout not working

### ISSUE THREAD

**Issue by smarterweb** [thirtybees/thirtybees#1015]
latest 1.10 vanilla install using 5 step checkout.
when trying to click "proceed to checkout" nothing happens, console shows error:
An invalid form control with name='id_state_invoice' is not focusable.

**Comment by getdatakick** [comment]
I can't reproduce this problem. Please provide more detailed repro-steps

**Comment by smarterweb** [comment]
I used the Softaculous installer to install TB 1.10
switched preferences->orders Order process type to Standard (5 steps)
try to purchase in frontend with instant checkout
click "proceed to checkout" and nothing happens,
then in dev console I see the error "An invalid form control with name='id_state_invoice' is not focusable." which triggers every time you hit that button

**Comment by getdatakick** [comment]
I still can't reproduce this. Instant checkout works fine on my local environment

**Comment by smarterweb** [comment]
did you try on a multistore environment? I sent you a pm in the forum with install details...

**Comment by getdatakick** [comment]
I was able to reproduce the issue. The requirement is to use some country with states (for example US) as default country. 

In that case, browser-side validation will expect invoice state to be set. The invoice state select field is located inside billing address area that is hidden by default. One has to tick the 'Different billing and shipping address' button to show it. When the area is displayed, the problem is more apparent. 

The fix is to fix validation -- do not require invoice state to be set when checkbox is not check. Fix should probably go to both Niara and Communit Theme

**Comment by getdatakick** [comment]
Alternate fix would be to get rid of this client-side validation for this field. All other fields on this page already depends on server-side validation only.

**Comment by getdatakick** [comment]
Fixes integrated to both themes

**Comment by unbranched** [comment]
The issue is exactly what described by @getdatakick and is not fixed for me, just tried it.

**Comment by getdatakick** [comment]
@unbranched are you using latest version of niara or community theme?

**Comment by unbranched** [comment]
Niara v 1.1.0

**Comment by getdatakick** [comment]
Well, this is fixed in bleeding edge only. Will be released as part of next tb version

**Comment by unbranched** [comment]
I consider this an important bug, any ETA for tb next version?

**Comment by getdatakick** [comment]
New TB version will be released by the end of next week (March 5).

Meanwhile, you are free to download the niara theme from the git repository and use it already.

**Comment by unbranched** [comment]
Oh I can wait next week, that's great news! Thanks a lot for you work!
