### ISSUE TITLE
Composer With repositories

### ISSUE THREAD

**Issue by mauroagr** [thirtybees/thirtybees#1028]
Dear,
In my composer i was using some repositories to run sdk from payments.
When use the coreupdate, the composer are erased and 'removed' all extra repositories in composer.
Have some method that i can use personalized composer and stay using coreupdate
Thanks
Mauro

**Comment by Traumflug** [comment]
If I understand you correctly, your _composer.json_ gets overwritten. Core Updater doesn't remove files (e.g. in _vendor/_) which were neither in the previous release nor the release updated to, unless explicitely told to do so (all these checkboxes in the obsolete files list).

Well, that's by design. Core Updater updates to a version, overwriting changed/distinct files is the whole point of it. But one can find previous files not matching the previous release in _adminXXX/CoreUpdaterBackup..._ and restore from there (after investigating what was changed).

**Comment by Traumflug** [comment]
Not a bug.
