### ISSUE TITLE
Geolocation Whitelist corrupted by saving

### ISSUE THREAD

**Issue by techjp** [thirtybees/thirtybees#1068]
The default geolocation whitelist, stored in the `tb_configuration` table under `PS_GEOLOCATION_WHITELIST` looks like this:

127;209.185.108;209.185.253;209.85.238;209.85.238.11;

It's much longer of course, but each IP is separated by a semicolon. It loads into the back office Preferences -> Geolocation with one IP per line, and no semicolons are visible.

However when you click on the Save button in the back office the data is saved to the `tb_configuration` table as follows:

127209.185.108209.185.253209.85.238209.85.238.11

The saved data has no separators in it and when reloaded into the back office the list looks like this:

![image](https://user-images.githubusercontent.com/7457115/65837181-4c9f7f00-e32f-11e9-9511-ef496e1c49f8.png)

**Comment by ksimunovic** [comment]
This field is saved in database two times, first correct and then incorrect, which overwrites the first one and then you get what you are describing.

First, the correct database save happens [here](https://github.com/thirtybees/thirtybees/blob/1.1.x/controllers/admin/AdminGeolocationController.php#L132) where the value gets converted to a single line, semicolon-separated list of values 

Few lines later parent::processUpdateOptions() is called which in the end updates this field in the database again but this time getting the value from Tools::getValue() [here](https://github.com/thirtybees/thirtybees/blob/1.1.x/classes/controller/AdminController.php#L4488). This value is containing new lines, which later get clean up in [Configuration.php:updateValue()](https://github.com/thirtybees/thirtybees/blob/1.1.x/classes/Configuration.php#L638).

@Traumflug Obvious problem is that the second update is not using correct value but what I'm not sure is what would be the correct way to avoid this behaviour in AdminControllerCore:processUpdateOptions(). Would it be using $options['type'], which is set to textarea_newlines or some other way?

**Comment by Traumflug** [comment]
Database getting updated twice is a problem where the programming model has no elegant solution for, AFAIK. The less elegant solution is to remove these entries from `$_POST` after doing a custom update in `processUpdateOptions()`, so they don't get found later.

And yes, this probably applies to all code in `processUpdateOptions()`, and to all classes overriding this method. A little code review for all these overrides wouldn't hurt.

**Comment by ksimunovic** [comment]
Unsetting or setting POST value to null didn't help because AdminController:processUpdateOptions() goes over AdminGeolocationController:$field_options which contains PS_GEOLOCATION_WHITELIST and then tries to get this value from POST/GET at:

https://github.com/thirtybees/thirtybees/blob/53c484ae076bf0cbaceb65ab4792915ef69beddf/classes/controller/AdminController.php#L4488

which in the end empties field in the database.

**Comment by getdatakick** [comment]
I believe the proper solution is to use define callback method: `AdminGeolocationController::updateOptionPsGeolocationWhitelist`, and remove the special handling of this field from `AdminGeolocationController::processUpdateOptions`. This way, `AdminController` will call this callback, and the value will be saved into database only once.

Proposed solution is in commit 1370db6a8a9822dc87875596c3d50db946b16d9f. 

It contains more code, but that's because it also fixes bug with ip address validation (there was none)
