### ISSUE TITLE
get order payments by $idOrder is broken

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1198]
In class OrderPayment there is a function **getByOrderId($idOrder)**, which is obviously broken. It searches for an id_order column, but in reality there is no such column.

We could debate long, why there is no id_order but only an order_reference column. But as the fix is quite easy, I will just propose a PR, that solves the issue for now.

**Comment by getdatakick** [comment]
Thanks for the fix. 

The reason why there's no id_order in the table is because of order splitting. One cart can generate multiple orders. The order reference is the common denominator - payments, invoices are using this reference code (they are actually shared between multiple order objects). This is of course stupid, there should have been only one Order object, with multiple sub-objects of type Package. Maybe in the future :)
