### ISSUE TITLE
Serious problems with HomesliderPro module

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1260]
I am using Homesliderpro module (=Sliders Everywhere!) version 1.6.41 by Syncrea. 

In Homeslider is installed I get the following problems:
 - When I go to the Settings->CMS page in the backoffice I get a 500 error. Debug mode doesn't work and no errors are produced in the log file. After some searching I found that the error occurs when the Dispatcher tries to load the file /modules/homesliderpro/controllers/admin/AdminCmsContent.php.
 - As far as I can see Homesliderpro has no override file
 - When I rename or delete the modules/homesliderpro directory I get a "Controller is not found error" when I try to access the Settings->CMS page.

Initially I had also some uninstall problems but these disappeared after gong back and forth in TB version.

**Comment by getdatakick** [comment]
I tried to install this module on my 1.1.x:

1) module could not be installed at all -- mysql server failed to execute sql 

```sql		
			CREATE TABLE IF NOT EXISTS `tb_sesliders_slideconf` (
				`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
				`id_shop` int(10) unsigned NOT NULL,
				`id_hook` varchar(255) NULL,
				`conf` text NULL,
				PRIMARY KEY (`id`, `id_hook`)
			) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
```
with exception `All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead`.

This is **not** thirtybees fault, it's a bug in the module

2. After I fixed the table creation, I was able to install the module. Module installs new *dummy* tab `AdminCmsContent`, which ensures that when you click on 'CMS' menu item, the module controller is opened instead of core controller.

While this is questionable approach, it works. Nothing wrong here

3. When I clicked on 'CMS' menu, I indeed received 500 error page. In my server's error log there was error message:

`PHP message: PHP Fatal error:  Declaration of AdminCmsController::viewAccess() must be compatible with AdminControllerCore::viewAccess($disable = false) in /modules/homesliderpro/controllers/admin/AdminCmsContent.php on line 257`

If you don't see such error message in your server's error log then you have misconfigured your server's error reporting.

The error message clearly states what is the problem. This controller extends AdminControllerCore and overrides method viewAccess. Module author forgot to include parameter `$disable`. In earlier php versions this was allowed. In newer php versions this is forbidden.

Again, this is bug in the module. Not in the thirtybees core. 

Note that the `$disable = false` parameter is present even in ps16. It's not thirtybees injection.
