### ISSUE TITLE
CategoryCore::getName returns one letter if object is created with id_lang passed to constructor

### ISSUE THREAD

**Issue by seigieu** [thirtybees/thirtybees#1277]
https://github.com/thirtybees/thirtybees/blob/1.1.x/classes/Category.php#L2147
If object is loaded as single language then `$this->name` is a string. 

This will return letter of index = $id_lang.

Possible solution: Check if if `$this->name` is string, and if is return it ignoring language.

---
Not making pull request, cause not sure how you would want to handle it. One way is above, but since it accepts `$ld_lang` as parameter, you might want to actually honour that parameter and query.

**Comment by getdatakick** [comment]
Definitely a bug. The method should check in what context was object loaded (all langs / single lang). If the requested lang is not available, then query db.

**Comment by getdatakick** [comment]
I don't believe it's an overkill. It's just a failsafe solution.

>If I want to use less memory and load categories with language set, then using getName now generates additional queries.

Yes, but without this fix the getName() would return single character only, because $category->name would be string and not array. 

This method is not used by core, or by any of the default themes, at all. It exists for backwards compatibility only, it is probably be used by some modules. We can't be sure. If the method was used on category instance loaded in single language context, it never returned correct  results, so it's quite safe to expect that such usage was not frequent. Module developers would probably detect this, and used different way to access the data.

Now the method will return correct result, but with performance penalty. Yes, we could invest into some caching, but that would be even bigger overkill. If there is a need for something like that in the future, we can always implement it.

Nice catch about the double variables. Will fix this.
