### ISSUE TITLE
Galera Cluster

### ISSUE THREAD

**Issue by acs-ferreira** [thirtybees/thirtybees#134]
Prestashop doesn't install on Galera Cluster because of `auto_increment` and `offset` needed to be set to `1`.

Any chances that this can be fixed on ThirtyBees?
http://forge.prestashop.com/browse/BOOM-2305

**Comment by firstred** [comment]
Chances are slim. The whole framework depends on the availability of
auto_increment. Even if we would fix it you would still be stuck with
broken modules.

**Comment by Dh42** [comment]
Doing this right now will break so much compatibility that nothing would work, so its not in the immediate future. It is however something we have talked about and can be added in a later version. 

See in forking the framework we have done it to address specific issues, mainly features and scalability. We have started to work on both, but this is a big one that will take time. It is likely something we are going to save for a 2.0 version because it would require every module and theme to be rewritten. 

What size site are you thinking you are going to deploy with a set up like this? We have deployed multiple sites handling 100m or more users a month on standard replication / read nodes.

**Comment by acs-ferreira** [comment]
We already have this set up, Multi-master replication on top of MaxScale, but the only way to install Prestashop is installing it on single or master/slave environment then replicate the data to the Cluster.

Once the data is on the Cluster, Prestashop works smooth, only installation fails...

But i understand that this is too much work that reaches a small group of users.

**Comment by firstred** [comment]
thirty bees is happy with any `auto_increment`ed ID. If you have three masters and if they all have their unique sequence of `auto_increment`s, it could work. I found this recommendation: https://mariadb.org/auto-increments-in-galera/

You basically let
- master 1 assign 1, 4, 7
- master 2 assign 2, 5, 8
- master 3 assign 3, 6, 9

I think that could work

**Comment by acs-ferreira** [comment]
I'll give a try to `wsrep_auto_increment_control` variable.

**Comment by firstred** [comment]
Interesting how Galera cluster already handles it. Please let us know if setting `wsrep_auto_increment_control` to `ON` works. I'm really curious.

**Comment by acs-ferreira** [comment]
As i thought, it is already `ON`.

![](http://s21.postimg.org/pd9c7pgrb/screenshot_246.png)

Confirmed here: https://www.percona.com/doc/percona-xtradb-cluster/5.5/wsrep-system-index.html#wsrep_auto_increment_control

So i think this should be turned `OFF` to works, and Percona clearly states it:
> This may not be desirable depending on application’s use and assumptions of auto-increments.

As i can't do this on production, i'll give a try on a dev. environment.

**Comment by firstred** [comment]
Is it `ON` on every master?

**Comment by acs-ferreira** [comment]
Yes, as it is `ON` by default on every Galera Cluster installation. Every node binged up is `ON`.
