### ISSUE TITLE
Categories disapear after edit and require displayed checkbox twiddling to show up again

### ISSUE THREAD

**Issue by gingerling** [thirtybees/thirtybees#1363]
https://greencloud.gn.apc.org/index.php/s/f2bg89Gocpz4dNc
Here is a video showing the issue

Steps: 

edit a category and save it - make sure it's still toggled a visible.
Check the side bar, its not visible
go to category list and unchecked then recheck the displayed? tick
Refresh shop page, now it's visible.

tb 1.1.0

**Comment by getdatakick** [comment]
Reproduced the issue.

The problem is with category group handling

1. When category is created or updated by AdminCategoriesController, property $groupBox is populated properly, and groups are saved to database.
2. When category is created or updated programatically, and property $groupBox is not populated, then groups are initialized to default values

Example:
```
$category = new Category(123);
print_r($category->getGroups()); // result = [1]
$category->active = true;
$category->save();
print_r($category->getGroups()); // result = [1, 2, 3]
```
