### ISSUE TITLE
Supply Orders > Pending receipt. Bug associated to the front office.

### ISSUE THREAD

**Issue by firstred** [thirtybees/thirtybees#141]
see https://forum.thirtybees.com/topic/87/supply-orders-pending-receipt-bug-associated-to-the-front-office

**Comment by TobyMudito** [comment]
This is still no fixed :)

**Comment by TobyMudito** [comment]
Hello to everybody.

After testing the problem deeply. I have realized that there is a way to avoid this problem:

In the supply order states configuration page, you just have to uncheck the Pending receipt option for the third state (Pending receipt).

Unchecking this field, when a supply order is changed to the state Pending receive, the Stock Available doesn't change and the front office shows the right value. So, problem fixed!! 

I don't like that by default this option appears switched on, because a lot of people can be confused, but at least, this is the way to fix it.

Regards!!!!

**Comment by firstred** [comment]
Thanks for sharing the solution!
