### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ugintl** [thirtybees/thirtybees#1449]
When I try to install it, I see following ajax error

![thirtybees-install-error](https://user-images.githubusercontent.com/12570802/172150728-bf36bc09-9f34-43a7-b7ca-83a7bb085ae2.jpeg)

**Comment by getdatakick** [comment]
What php and database version are you using?

**Comment by ugintl** [comment]
php 7.4 and mysql 5.7

**Comment by getdatakick** [comment]
These two are supported. Please look into your thirty bees installation '/log' directory to see if there is any error message. Also, look into your server error logs for the same.

Without actual error message it's not possible to move forward with investigation.

**Comment by musicpanda** [comment]
Just wondering: why should people look in the error log file? That can be quite cumbersome and some servers don't even keep track. And there is nothing secret about this error message: when one has the right to do an installation one is supposed to have the rights to see the error messages.

I can understand the desirability of a clean interface. But isn't it at least possible to have the error messages at least under a button?

**Comment by getdatakick** [comment]
@musicpanda There is already code that displays error message, but only when server returns it:

https://github.com/thirtybees/thirtybees/blob/8023d2bda70b6995bde73456439d126ed1c2845d/install-dev/theme/js/process.js#L64-L102

Ajax handler expects response to be valid json, with `success` flag informing about operation status. If operation failed (exception was caught), then the `message` property contains exception message.

Sometimes, however, the response is not valid json. This can happen for many reasons, for example

- proxy server can reject response from php server, for example because of large headers
- application produces unrecoverable error (not even exception) and is not given a chance to handle it. For example, syntax error
- and there are more

When these situations happen, the response is a generic html page, and we have nothing to display. User needs to investigate where the error originated (php / proxy) and look into the appropriate log files. For example, unrecoverable errors are logged in apache / php-fpm logs.

**Comment by musicpanda** [comment]
Nine out of ten cases the exception is not valid json. And even when it is the information is often so generic that it is unusable. 

I would prefer to see installation in debug mode so that you can see PHP errors too. Strip html tags and the message can be displayed.

For Prestools I deliberately use iframes instead of Ajax to make errors more visible.

I noticed when I recently implemented for someone a new A2 hosting account that it doesn't by default register the errors. You have to switch that on. And this is one of the recommended providers.

**Comment by getdatakick** [comment]
In most cases (99%) it is valid json, since php application code ensures that, see the request handler code:

https://github.com/thirtybees/thirtybees/blob/f30d2079e9dadcde21a1daa12bed2c85d183f390/install-dev/trystart.php#L38-L41

https://github.com/thirtybees/thirtybees/blob/f30d2079e9dadcde21a1daa12bed2c85d183f390/install-dev/classes/controllerHttp.php#L525-L530

Then only situation when response (to ajax request) is not valid json is when same fatal error occurs, and php script is prematurely terminated. In that case, php server itself (not an application) handlers output

**Comment by musicpanda** [comment]
The question that started this thread is typical for installation errors. People see that the installation stopped at a certain percentage and they have no idea why. I have repeatedly experienced it myself too - and I cannot remember even a single time when useful information about the cause was provided.  The Prestashop forum contains quite a lot of this kind of reports too. 

> Then only situation when response (to ajax request) is not valid json is when same fatal error occurs, and php script is prematurely terminated. In that case, php server itself (not an application) handlers output

That is what you need debug ('_PS_MODE_DEV_') mode for. There should at least be an option in the installation forms to have everything run in debug mode.

**Comment by getdatakick** [comment]
Debug mode has no impact on error reporting, not during installation phase anyway. Any errors / exceptions that **can** be caught on application level are caught, and displayed (see the snippets above). Depending on request method, it is either displayed as debug error page, or error message is send in `message` property of response json (in case of ajax requests).

Errors that can't be caught by application... well there is nothing we can do about that, as we **can't** catch them. It is php server responsibility to log these kind of errors. From application point of view perspective, there is not much that can be done to mitigate this issue.

**Comment by ugintl** [comment]
@getdatakick @musicpanda I do not know about the technical details, but whenever a php application does that, a page refresh solves it. This however, seems something different.

**Comment by Maloupi** [comment]
I just got the exact same bug with Thirtybeed 1.6.0 on Windows/PHP 8.1 with a net::ERR_CONNECTION_RESET from ajax request.
Ajax request failed for process initializeClasses=true with error.
I tried many things (page reload, http/https...).
The only thing which worked was to use PHP 7.4 !
