### ISSUE TITLE
BO: Free products in order not possible

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1466]
It's not (or no more!?) possible to add products to an order and set the price to 0.00. 

What might sound a bit strange is not so a rare case. Often you have to replace an item for free or you just want to make a gift.

**Comment by getdatakick** [comment]
I don't have any issues with such products. Tested on bleeding edge. What issues exactly are you experiencing?

**Comment by eschiendorfer** [comment]
Oh that was quick.

I am talking of this one (basically adding when the order is already existing):

![image](https://user-images.githubusercontent.com/15154932/179481237-7640e8c9-d571-4173-9e25-a20cc7a1bda3.png)

While doing it again. I notice, that it's probably possible to add with price of zero. But it's not possible to edit it to zero. Can you confirm that?

**Comment by getdatakick** [comment]
Reproduced. Back office, order line modification, set price to zero -- javascript validation error occurs. 
Note that it is possible to add new order line with zero price, we just can't set the price of existing product to zero for some reason. Which is weird, since the code exists in add order item handler as well.

References:

https://github.com/thirtybees/thirtybees/blob/2be8509c0ae014898da1e6054e81cb460376fda7/js/admin/orders.js#L729-L732

https://github.com/thirtybees/thirtybees/blob/2be8509c0ae014898da1e6054e81cb460376fda7/js/admin/orders.js#L519-L522
