### ISSUE TITLE
Image regeneration much too slow

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1480]
It took me some 5 hours to regenerate 800 images. This is not workable. When I look in the error log I see it full of messages of timeouts. Always on one of three lines (363 is the most common). 
`*ERROR* 	2022/08/01 - 21:00:46: Maximum execution time of 30 seconds exceeded at line 316 in file classes/ImageManager.php
*ERROR* 	2022/08/01 - 21:01:16: Maximum execution time of 30 seconds exceeded at line 363 in file classes/ImageManager.php
*ERROR* 	2022/08/01 - 21:01:46: Maximum execution time of 30 seconds exceeded at line 420 in file classes/ImageManager.php`

It puzzles my why this takes so long. This is Panda so there are a lot of high res images.

**Comment by musicpanda** [comment]
The error message doesn't make sense:
![errormsg](https://user-images.githubusercontent.com/13930107/182222758-5163f83b-2226-4020-8f1b-f2d21a8c1fd8.jpg)

**Comment by getdatakick** [comment]
There is not much we can do about performance issue. There is very minimal overhead in PHP code, the most time is spend in native GD library. Of course, we could try to use different library / mechanism, but I doubt there would be much performance improvements.

Your source files are probably very large, so it takes GD a lot of time to resize them into all formats. You could also try to tweak quality settings.

Regarding timeout -- again, nothing we can do about this one. We are calling native library function, and this function has no input parameter to specify maximum allowed execution time. We don't know upfront how long it will take, also.

There are plans to implement image generation workqueue task, so that the process would not have to run using ajax calls. Also, such implementation would allow you to execute task using php CLI, which would not be affected by timeouts.

The other issue -- the very funny error message - is tracked in issue #1481
