### ISSUE TITLE
Core FO js files should not use jQuery

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1485]
I am coding a theme without jQuery. Yeah you read correctly :)

I am noticing that the files /js/tools.js and /js/trigger.js use a few lines of jQuery. That should be replaced with vanilla JS. It's a first very little step to remove depency of jQuery in FO.

Note: It's also not super nice, that jQuery is forced to load in https://github.com/thirtybees/thirtybees/blob/fa40d7e668aa9d8a2cc32d3faef59b856d903fed/classes/controller/FrontController.php#L1057. A theme setting, that allows to skip it would be nicer. But for the moment I can live with an override on my side.

**Comment by getdatakick** [comment]
I agree that core js files should not depend on jquery.

However, it will be very hard to remove the jquery library, as there are a lot of modules that depends on it. And they do not include it themselves, but simple expects its existence.

Similar applies to stuff like `.hideOnSubmit` -- it doesn't matter that the theme is clean and does not depend on these hacks. Because modules can depend on it, and they can be included in clean themes as well.

**Comment by eschiendorfer** [comment]
Sure. I would never remove jquery blindly. But I would just like to waive it in my case as I basically only use core, core modules and my modules. What would you recommend then? 

Should I just not load tools.js and copy the functions I need from there? It seems, that almost nothing is needed for me. As far as I understand tools.js is a mixture between FO and BO stuff.
