### ISSUE TITLE
Using php-function "strpos" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1615]
Message:
Using php-function "strpos" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

Location:
vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php line 114

I have this deprecation on both my active shops.

**Comment by getdatakick** [comment]
Should strpos be really smarty modifier? In my experience it is mostly used in templates inside {if} statements

```smarty
{if $variable|strpos:"index"}
  ...
{/if}
```
Which is quite weird syntax for if statement. Developer should use standard function call instead
```smarty
{if strpos($variable, "index")}
  ...
{/if}
```

Modifiers should be used mostly for output modification. Something like

```smarty
<a href="$variable|escapeUrl">link</a>
```

But because there are modules with this weird syntax, maybe we could add support for this. Feel free to propose pull request. See this commit for reference: https://github.com/thirtybees/thirtybees/commit/2df5dda05b5d406f238f5e44c2086f6a814a844e
