### ISSUE TITLE
encryption warnings

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1740]
I just updated to the bleeding edge. Now my php error log is flooded with the following two messages:

PHP Warning:  PHP Encryption can't be used because _PHP_ENCRYPTION_KEY_ constant is not defined. Using Blowfish encryption instead. in \\classes\\Encryptor.php on line 167, referer: /admin/index.php?controller=AdminDashboard

PHP Warning:  Blowfish encryption is deprected and will be removed in next version of thirty bees. Please use PHP Encryption instead in \\classes\\CryptBlowfish.php on line 487, referer: /admin/index.php?controller=AdminDashboard

Note also the typing error in "deprected".

**Comment by getdatakick** [comment]
Exactly as @therampagerado suggested.

There was a bug in one of the old versions of thirty bees (1.1.0 or even older, I don't know) that let you switch to 'PHP Encryption' but did not generate `PHP_ENCRYPTION_KEY` key.  Because of the lack of the key, thirty bees could not use the 'PHP encryption', and used fallback method instead - slow blowfish.

Thirty bees 1.5 now raises warnings when `PHP_ENCRYPTION_KEY` is missing (and 'PHP Encryption' method is selected). 

The fix is to either manually create encryption key, or simply switch to blowfish encryption, and than back to php encryption. This switch will generate new key if none exists.
