### ISSUE TITLE
changeIdOrderState fatal error on OrderCore instance

### ISSUE THREAD

**Issue by seigieu** [thirtybees/thirtybees#1749]
You may not always want to use `new Order`. But using following code:

```php
$oc = new OrderCore(1);
$oc->setCurrentState(1);
```
Will produce fatal error, becauseL
- Firstly changeIdOrderState does not return any false nor error. Nothing.
- If changeIdOrderState 2nd parameter is `OrderCore` instance then it will return on 2nd check.

That will result in calling addWithemail fatal error.

There are 3 ways to fix it:
https://github.com/thirtybees/thirtybees/blob/1.5.x/classes/order/OrderHistory.php#L99
- Change this line to check against `OrderCore` instead of `Order`

And additional things to do would be either: 
- To to return false and check its value in setCurrentState (setCurrentState does not return any value either by the way)
- And third would be to throw some exception with meaningful description of problem like: "Provide valid ID or Object".

**Comment by getdatakick** [comment]
Instantiating *Core classes should not be done, because it would essentially bypass any overrides that might exists. This would make entire system more unpredictable and chaotic.

**Comment by seigieu** [comment]
Partly agree on that. but:
- if that's the case, why are Core classes not abstract? If they'are not abstract, they are meant to be used
- And there might be cases where you do not want to use Overriden class. For testing estc.

So I think these classes should Either be Abstract (that would make system more predictable and not chaotic), or be allowed to be used.

Even if not then I still think it's a good idea to notify developer that he used wrong class at last, especially if it's causing fatal error.

**Comment by getdatakick** [comment]
I agree, core classes should be abstract. Unfortunately, original PS developer didn't make them that way, and we can't do that now due to backwards compatibility. There are some modules that instantiate them, unfortunately. 

For unit tests, overrides are not used. For e2e tests, they are of course used. That's correct. Tests should run in clean repository in the first place. But you can run them in dirty repository as well, to check that your shop-specific overrides do not cause test failures.
