### ISSUE TITLE
Simplify Tools::getRemoteAddr against IP Spoofing

### ISSUE THREAD

**Issue by gregzawadzki** [thirtybees/thirtybees#1817]
I think this method requires some modification, or simplification.
It really is good to know "real" adress of someone who came. But recently robots take adventage of it and mask themselves with it.

I see many connections to our sever from "google proxy" ips. When I however enter server logs, at this time i have `"POST /contact"` spam. So basically i can't use backoffice (connections) to ban IP, as I would ban wrong person/entity and spam would flow.

I think it should be reconsidered to change this to just `return $_SERVER['REMOTE_ADDR'];` or implement logging of real and source IP addresses in connections.

Will not make PR since I wanted first to know what you think.

**Comment by getdatakick** [comment]
I don't see any problem in the code as it is.

It is true that attacker can pass any value in `HTTP_X_FORWARDED_FOR` header. However, this value will be used only if the REMOTE_ADDR (actual peer ip address) is within IP ranges used for local communications within a private network

- `10.0.0.0/8`
-  `127.0.0.0/8`
- `172.16.0.0/12`
- `192.168.0.0/16`


Because `REMOTE_ADDR` header can't be modified, the attacker must either
- perform attack from within your private local network
-  or you must have some reverse proxy (nginx) in from of your PHP server that forwards all requests and includes HTTP_X_FORWARDED_FOR header as well. In this case, PHP server sees nginx IP address as REMOTE_ADDR, and allows HTTP_X_FORWARDED_FOR header. In this case, you need to properly configure your nginx settings, and block forwarding HTTP_X_FORWARDED_FOR header 

Or is there something that I overlooked?

**Comment by seigieu** [comment]
In my case it was that connection logs displayed an IP Address that do not exist in server logs (but it should). So I assumed that this function allows IP Forgery. Will set some logs to log what this returns and what REMOTE_ADDR really have and will come back in few days.
