### ISSUE TITLE
Color swatches are broken.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1855]
I had configured many color combinations using swatches, like - White-Green, Blue-White, etc. (many clothing I sell are duo color).

Now I went there to add more colors and all colors using the swatches show white background and when I open them the texture that I uploaded are not there. The bad thing is that I tried uploading them again and nothing is saved.

Could this be a result of the recent image rewrite?

Also the color layered navigation filter is gone on all places it should be shown. I just noticed that as most of the items have no color combination. Reindexing does not help. Could this have to do with this update as well?

![image](https://github.com/user-attachments/assets/f31fef66-767a-40cb-a427-4e994115d95b)

**Comment by therampagerado** [comment]
@getdatakick  the only issue that I have left is with the color filters. They are now not showing in any other shop other than the default one. Everything in my layered navigation module is enabled and configured. Also 100% sure they were working as those textures are for those additional shops only and I played long time to configure them.

Could this be something inherited from the image rewrite too?

**Comment by getdatakick** [comment]
@therampagerado blocklayered module works fine in my dev environment. 

I found an issue with niara theme template override `themes/niara/modules/blocklayered/blocklayered.tpl` line ~130 - it incorrectly constructs background url `img/co/{$id_value}.jpg` instead of `/img/co/{$id_value}.jpg`.  Also, this template expects jpg, which might not be the case anymore. 

Apart from this template override issue, the functionailty works good.

**Comment by therampagerado** [comment]
@getdatakick thank you!

I'll investigate further. I use Warehouse and it's LNM displays .jpg for the textures and they show.
