### ISSUE TITLE
Regenerate thumbnails doesn't work

### ISSUE THREAD

**Issue by projectmb** [thirtybees/thirtybees#1862]
I upgrade to bleeding edge on 18 Aug 2024. All the images disappears and the Regenerate thumbnails doesn't work.

**Comment by getdatakick** [comment]
Hard to tell what can be wrong. 
- Try to regenerate .htaccess file.  
- Check what your image types looks like (Preferences > Images), and that they are associated with correct entities (products, categories, ...)

**Comment by projectmb** [comment]
the issue is in admin: Preferences > Images,  when pressing generate images nothing happens

**Comment by projectmb** [comment]
to give more insight, I have upgrade TB version to bleeding edge today and all the thumbnails disappear from both admin and frent-end. Do I have tried to regenerate the images in Preferences > Images but nothing happens. So i have to restore the backup.

**Comment by getdatakick** [comment]
I can't reproduce this. I suspect the problem will be with the overrides / third party modules

**Comment by eschiendorfer** [comment]
Probably it's not related, but one thing I notice on my site: getting images by new Link(); can fail. 

It returns me the url without any http:// or https://, which means that the browser adds this again leading to something like: https://www.domain.com/www.domain.com/img/bla.webp

Previously the following was working:
```
$link = new Link();
$link->getImageLink($params);
```

Since bleeding edge, I have to use:
```
$link = new Link(null, Tools::getShopProtocol());
$link->getImageLink($params);
```

or:
```
$context = Context::getContext();
$context->link->getImageLink($params);
```

Is this intended? I haven't found any issues in the core. But I guess modules could easily have the "broken" way.
