### ISSUE TITLE
Product import: text when backorder allowed duplicated to other languages too.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1884]
thirty bees version: edge

Multistore: yes

1. I'm importing products that have 'text when backorder allowed' set for the my default language (Bulgarian):
text when backorder allowed
2. I'm importing for Bulgarian (BG is default lang, but even if I import for EN it's the same):
![image](https://github.com/user-attachments/assets/347b9dfc-4601-4842-a369-77b51ef05a69)
3. The value for BG language is copied to EN too:
![image](https://github.com/user-attachments/assets/30c2b7ff-6451-421a-8121-d22826ff5d13)

**Comment by getdatakick** [comment]
This is expected behaviour.

When you create new entities using import, all translatable fields will share the same values in all languages.

The **Language of the file** language is used only when you update existing entity (to do that, you have to check **Force all ID numbers** and/or **Use product reference as key**). In that case, only only one language is updated

The import flow for multiple language should be:

1) import all fields, including translatable fields, in first initial import for the default language
2) import only translatable fields for every language in the system
