### ISSUE TITLE
Attempt to read property "id_product" on int

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#1916]
@getdatakick 
https://github.com/thirtybees/thirtybees/blob/70aa410f4a970d6271d4a49aee47f96d02c3769f/classes/order/Order.php#L2873-L2880

```$cartRule->description``` is a string, ```$cheapestProduct?```

sorry I cannot submit a proper PR because I am not familiar that much with cart rules.

**Comment by getdatakick** [comment]
When cart rule that applies to 'Cheapest product from selection' is used, thirty bees will determine cheapest product at the time of order creation.

Because order can be later modified in back office (the chapest product can change), the selected cheapest product must be somehow memorized.

Somebody decided that it is a good idea to create a new, single use cart rule to remember this information. New cart rule is generated during checkout. This rule is a standard discount that applies to entire order, and has monetary value that matches the value of the cheapest product. Also, information about cheapest product is remembered in cart rule `description` field (as a serialized json object).

When generating product tax breakdown we need cheapest product id information.

The code simply attempted to json decode 'description' field, and then used the result:

```php
    if ($cheapestProduct = json_decode($cartRule->description)) {
    }
```  

This check worked when the description contained regular text, or when was empty. In that case, json_decode returned false.

However, this check failed when the description contained a simple number. In that case, 

```php
json_decode("123") === (int)123
```

The condition matched, and the executed code caused warning, and potentially wrong tax breakdown.
