### ISSUE TITLE
Installer works in mode_dev only?

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#217]
I think it's the second time that somebody reports the installer working in developer mode, only:

https://forum.thirtybees.com/topic/256/can-t-install-1-0-1-gives-500-and-white-screen-on-install/12

**Comment by alwayspaws** [comment]
I don't want to be the third to have this problem, so I'm waiting it out. I'm waiting for other reasons, too, before trying to install thirty bees.

**Comment by Traumflug** [comment]
With everybody just waiting, this waiting will take forever. It'd be much better if you'd try whether this is actually true. And which files are missing with a regular installation. Or what exactly doesn't work. Such testing can be done by everybody.

**Comment by roband7** [comment]
I installed 1.0.1 just fine, and didn't have to enable mode_dev.

Besides, the error message given in the first post here happens before mode_dev is ever set to either true or false, so I'm not buying that theory.

My guess is some sort of file permission error.

**Comment by alwayspaws** [comment]
I've been reading thirty bees posts and see that there are various fixes and updates for many issues.

Are these updates being incorporated into the latest thirty bees install?

When brand new visitors come along, how would they know where to start with updates?

If you don't incorporate all the updates into the initial install and the initial migration tool, can you notify us in one summary post per day or per week as to what we should update? 

To me, constant updates are a major concern, since I'm still working on getting my products on my original site, so I can't install thirty bees or migrate until then.  

 I really want a fresh start, so if I'm understanding correctly, I can install thirty bees and import my categories and products,  as well as copy the contents of my CSS pages and other information from my currently working site over to thirty bees. 

I'll post this in the thirty bees forum also.

**Comment by Traumflug** [comment]
Here's another one of these reports: https://forum.thirtybees.com/topic/265/update-results-in-near-empty-homepage-and-other-trouble

> The home page displays only my logo and a black bar. When I switched MOV-DEV on I don’t see any errors.

He investigated a bit (excellent!) and found that some code tries to load index.php from a directory level higher. Shop is installed into a subdirectory of the server folder. Looks like some code isn't respecting the Shop URI and turning on MODE_DEV works around this problem.

**Comment by firstred** [comment]
Closing this one. If we find some useful info, let's create a new issue.
