### ISSUE TITLE
Request: add readme about tests

### ISSUE THREAD

**Issue by kpodemski** [thirtybees/thirtybees#23]
Please add proper docs on "How to test ThirtyBees installation" using codeception etc.

Simple guide to run tests locally.

**Comment by firstred** [comment]
Sure thing! But have to figure out the last pieces before I can start writing.

I'd love to share the information with other developers, so I'll definitely add an explanation!

**Comment by firstred** [comment]
Going to add this to https://docs.thirtybees.com => developer guide

**Comment by Traumflug** [comment]
I'm keen on running these tests, too :-) So I looked at the Travis CI logs and reverse engineered from there. Here's what I have so far, may it be a template for that documentation:

1. To not mess up the development shop it's a good idea to make a copy of the repository. Assuming web content goes to ```/var/www/html/``` and that directory not being user writable, it goes like this:
```sh
cd /var/www/html
sudo cp -rp ThirtyBees ThirtyBees2
cd ThirtyBees2
git remote remove origin
git remote add origin ../ThirtyBees
```

2. Then one has to get PhantomJS. Also PHP command line, but that's most likely already installed. Problem with PhantomJS is, Debian/Ubuntu packages come with Ghostview disabled, because Ghostview contains closed source blobs. See https://bugs.launchpad.net/ubuntu/+source/phantomjs/+bug/1578444 Closed source is often a source of trouble.

To work around this, one has to install the PhantomJS package manually. Download it from http://phantomjs.org/download.html, then do something like this:
```sh
tar -xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs $HOME/Linux/bin
```

3. After each development step in the development repository, one has to refresh the testing clone. Branch ```work``` is assumed to be the branch to test:
```sh
cd /var/www/html/ThirtyBees2
git checkout master
git branch -D work
git fetch --prune
git checkout work
```

4. Clean that testing repository from previous installations:
```sh
git clean -dxf -e vendor && git checkout .
```
No need to clean the database, the next command line installation can take care of this.

5. Next step ist to do a standardized installation. Codeception assumes database, user names and such stuff, this installation will set all this right, adjust database user and password to your local needs:
```sh
php install-dev/index_cli.php --newsletter=0 --language=en --country=us \
  --domain=127.0.0.1:8888 --db_name=tb.unit.test --db_user=root \
  --db_password=123 --db-clear=1 --db_create=1 \
  --name=tb.unit.test --email=test@test.test --firstname=test \
  --lastname=test --password=testtest
```

6. Codeception setup has stuff like database location, user and password hardcoded in ```codeception.yml``` Here an example on how to set a password after the above repository cleaning:
```sh
sed -i 's/password:.*/password: '\''123'\''/' codeception.yml
```

7. At this point one can run Unit and Integration tests already:
```sh
vendor/bin/codecept run unit,integration
```

8. Now let's get PHP and PhantomJS running in the background:
```sh
php -S 127.0.0.1:8888 -t . >/dev/null 2>&1 &
phantomjs --webdriver=4444 >/dev/null 2>&1 &
```
Note that it's perfectly fine to connect with a real browser to ```127.0.0.1:8888``` to see what PhantomJS sees.

9. Finally one can run GUI tests:
```sh
vendor/bin/codecept run functional,acceptance
```

10. Once being done with testing, one can stop PHP and PhantomJS:
```sh
killall -2 phantomjs; sleep 1; killall -2 php
```

**Comment by Traumflug** [comment]
With all this written, these GUI tests appear to be running pretty unreliably. 4 of 10 attempts work just fine, the other ones time out with tasks as simple as showing the first page. My first guess is that the web server built into PHP can't keep up with the high number of requests, but I didn't investigate this so far. Running the non-GUI test is fine for checking against accidental syntax errors, for example.

**Comment by mke-tb** [comment]
After two and a half year this issue is created and one and a half year after [PhantomJS development is suspended](https://github.com/ariya/phantomjs/issues/15344), what do you think the necessity or the priority of this issue?

Do you think it is worth investigating alternate solutions? @kpodemski @Traumflug

**Comment by Traumflug** [comment]
With some luck I'll manage to move my above post into a web page with better formatting before too long, maybe just to get rid of this issue report.

Regarding PhantomJS, that's currently in active use, every Travis CI run uses it. I also see no urgent reason to replace it as long as it works. thirty bees' testsuite isn't picky about the exact browser used, no tests for pixel-level accuracy.

Which means, just leave this issue open, no work needed either.
