### ISSUE TITLE
Not posible to set minimum quantity when products have combinations

### ISSUE THREAD

**Issue by elund** [thirtybees/thirtybees#263]
It's not posible to set minimum quantity when products have combinations. The field for minimum quantity is not shown under available settings. If I delete the product combinations then it works fine. i tried to google the issue and it looks like an old PrestaShop bug.

![image](https://user-images.githubusercontent.com/6267400/27510328-49ca1702-590e-11e7-9de2-ff0ce5d40c45.png)

![image](https://user-images.githubusercontent.com/6267400/27510312-1d6da372-590e-11e7-9af2-371d68285350.png)

**Comment by Traumflug** [comment]
Looking at the code ([admin-dev/themes/default/template/controllers/products/quantities.tpl](https://github.com/thirtybees/thirtybees/blob/1.0.x/admin-dev/themes/default/template/controllers/products/quantities.tpl#L224)) I see it's intentionally turned off. Accordingly not a bug, but a missing feature. Or an impossible feature.

You can turn it on by removing line 224 and 235 in this file. Question is: how many worms are in the can you open by doing so. Usually developers don't turn off features to upset their customers, but because keeping them enabled messes things up elsewhere.

Same for the availability date field, one can enable it by removing lines 268 and 285 in the same file.

**Comment by elund** [comment]
OK, then let us call it an inconvenient feature ;-)
When turning this of, the minimum quantity should be set to 1 to disable this feature.
My minimum quantity was by mistake set to 2 and I could not set it to 1.
But thanks for showing me the code :-)
