### ISSUE TITLE
Option to disable full page caching for logged in users

### ISSUE THREAD

**Issue by pucilpet** [thirtybees/thirtybees#295]
Some modules are problematic for logged in users, even if you add them as dynamic.

So it would be good to have this option.

**Comment by firstred** [comment]
Makes sense. Thanks for the suggestion!

**Comment by Traumflug** [comment]
Can we get away without yet another configuration option, please? Merchants have no idea on what to chose there.

I'd be fine with code always assuming this to be true ... until the underlying problem got solved.

**Comment by mke-tb** [comment]
> Can we get away without yet another configuration option, please? Merchants have no idea on what to choose there.
> 
> I'd be fine with code always assuming _TB_DISABLE_PAGE_CACHE_WHEN_LOGGED_IN_ to be true ... until the underlying problem got solved.

Okay, let's do it that way.

**Comment by mke-tb** [comment]
https://github.com/thirtybees/thirtybees/compare/issue-295 should fix this.

**Comment by Traumflug** [comment]
Excellent. Moved to _1.1.x_. Thank you very much.

**Comment by getdatakick** [comment]
I don't know the reason why FPC should not be enabled for logged in customer. All problems associated with this has been resolved for a long time now by adding customer id into [page key](https://github.com/thirtybees/thirtybees/blob/6358c7842e5463b2e9ad4575d48bb38ac8f385a5/classes/PageCacheKey.php#L37). 

If the reason is to decrease number of cache entries, then OK. In that case, you should remove customer ID from page cache. It's unused anymore, and can mislead other developers to think FPC can be used to cache data for logged in customers as well
