### ISSUE TITLE
Modules should be sorted

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#365]
In the Prestashop backoffice the modules are shown sorted alphabetically.

In Thirtybees there seems to be no order at all. 

Although far from perfect alphabetical order helps at least to a certain extent to put similar modules together and to keep an overview. The random order in TB serves no purpose at all.

**Comment by yaniv14** [comment]
I think the modules are sorted alphabetically in TB.
First it shows the modules you have in the modules root folder and after it shows all the rest of the modules that available from TB feed (also alphabetically).

**Comment by musicpanda** [comment]
Here are the first six of my list. Good luck finding any regularity in their order:
Advanced EU Compliance v2.0.2 - by PrestaShop
Bank wire v2.0.1 - by thirty bees
Advertising block v0.10.1 - by PrestaShop
Banner block v2.0.0 - by thirty bees
Top-sellers block v2.0.0 - by thirty bees
Cart block v2.0.0 - by thirty bees

**Comment by yaniv14** [comment]
Its being sorted by the module name and not the module readable title.
advancedeucompliance
bankwire
blockadvertisement
blockbanner
blockbestseller
blockcart

**Comment by musicpanda** [comment]
That doesn't make sense to me. You might as well sort them on size.

**Comment by firstred** [comment]
> That doesn't make sense to me. You might as well sort them on size.

:laughing: 

Yeah, there was a mix of indexed and non-indexed Module instances in the main module list array, I believe. Some were indexed by key, others were not. Since an associative array is much faster (modules in that array have to be accessed a lot, A LOT), we standardized it to that one, but this means you can no longer sort the modules properly, so we'll have to undo that. 
I am currently working on an unindexed array with a separate index for faster accessing. Should be available with 1.0.5, which means that until then you'll have the performance improvement, but without proper sorting.

**Comment by Traumflug** [comment]
@kublaios proposed a solution on [branch _issue-365_](https://github.com/thirtybees/thirtybees/commits/issue-365). Appears also in Core Updater.

**Comment by Traumflug** [comment]
Leaving the commented thing aside, this proposal works fine. Great!

**Comment by Traumflug** [comment]
[This discussion](https://github.com/thirtybees/thirtybees/commit/f899eae7a607899b48339bfbe3922dc1da257ef1#r34731181) is probably more visible here. My mistake to start it there.

@Traumflug
> These display names are translated, comparing them needs a mbstring function.

@kublaios
> We can take one step further and use Collate for this comparison, however we need to pass a locale to its initializator. Should we go for that by using the shop language?

@kublaios
> I used strcoll and I think it serves the purpose.
> https://www.php.net/manual/en/function.strcoll.php
