### ISSUE TITLE
Deleting products and combination not possible with asm

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#404]
It's not possible to delete products and attributes if you use advanced stock. Likely this is also related to multistore. 

Case 1: You accidently save a product in two stores. You want to delete it in one of them. You will get an error, that you can't delete a product which is in stock.

Case 2: You try to delete a combination in a product. You will get a similair error. Even if the stock is equal to zero

To be honest: ASM needs either to be seriously redone or dropped. I have already solved some issues, but there is no end sight. I can't recommend it anymore on this conditions. It's just completly unusable for normal merchants :(

**Comment by mke-tb** [comment]
> To be honest: ASM needs either to be seriously redone or dropped. I have already solved some issues, but there is no end sight. I can't recommend it anymore on this conditions. It's just completly unusable for normal merchants :(

Has this been changed?

**Comment by eschiendorfer** [comment]
Well I have customized our "ASM" so much, that I can't answer this question 100% for sure. But why would ASM became better, if nobody worked on it the last months?

**Comment by mke-tb** [comment]
Who knows, after all it's a hive so maybe the bees worked it out.

If that's not the case, I can still think of a couple of reasons:
1. ASM is a part of the product, it could've been that while someone is fixing something else, that fix somehow fixed this.
2. This issue is from 640 days ago, not from "the last months" so lots of things have been changed and some of them could've affected this one.
3. When you have pages of issues and some of them are older than 2 years, it's not optimal to jump into everything before making sure that they're still reproducible. From what I understand your "ASM" is not the ASM that other people use anymore so what is not working there might be working here or vice/versa.

It looks like the best solution for now is to focus on issues that are more core related and has feedback/interest from more people.
