### ISSUE TITLE
Product.js not obeying webp off

### ISSUE THREAD

**Issue by matrixino** [thirtybees/thirtybees#499]
Version 1.0.4
At line 208 it should be
`if (window.useWebp && Modernizr.webp) {`
instead of
`if (Modernizr.webp) {`
otherwise it keeps changing the extension on the main product image even if webp is off in image settings.
Also not sure if it's only my problem, but regenerate thumbnails don't regenerate webp images? So actually I can't turn webp on.

**Comment by Dh42** [comment]
It looks like the last commit commenting webp out was not included in the build. Can you add this commit and see if it fixes your issue, thirtybees/community-theme-default@50ad466#diff-80de5a68225b75989b82be078a4bddf2

**Comment by matrixino** [comment]
Oh I already fixed it myself as above. I supposed there was a commit left out, so I didn't create a pull request.
What about the regeneration? Seems like it regenerates only standard png/jpg, not webp. It's supposed to be still a work in progress?

**Comment by Traumflug** [comment]
There is no such thing in line 208, but how about line 212? https://github.com/thirtybees/community-theme-default/blob/1.0.x/js/product.js#L212 Is this the line in question?

And yes, @Dh42 is right, this commit wasn't picked into the release package, because it was pushed to the theme repo, but not committed in the core repo. It looks like we have to search for a more robust way to build releases.

**Comment by matrixino** [comment]
@Traumflug  Yes, but in the 1.0.4 zip it's 208, I think someone changed it later. This is after my change:

![image](https://user-images.githubusercontent.com/6110527/39592971-ca42e404-4f08-11e8-9ef3-383de0311bc9.png)
