### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by doclucas** [thirtybees/thirtybees#557]
Tested on WAMP with php 7.2, got a few simple "each" errors which I fixed.
The admin, on the other hand, doesn't seem to load at all and I can't find much in the error logs.
Any way to fix this?

**Comment by Dh42** [comment]
We might should branch to 1.1.x for this. What do you think @Traumflug that way we do not have to interfere with 5.6 compatibility.

**Comment by Traumflug** [comment]
Upgrading Smarty would be the golden solution. It's currently set to *3.1.19*, most recent version is *3.1.32*, see our *composer.json* vs. https://github.com/smarty-php/smarty/releases. This should bring compatibility with PHP 7.2.

However, there's most likely a reason why it's set to this older version, while all other composer dependencies update to the latest (bugfix) version. I didn't try hard to find this reason, yet.

**Comment by doclucas** [comment]
Its quite a bit upgrade. I just tried it today, but have up due to the bug v about it changes and my limited time.
Note that both php 5.6 and php 7 are reaching end of life in just a few months and your github.com project says you aim to be compatible with php 7.2, so needless to add that... Now is the best time :)

**Comment by therampagerado** [comment]
I think that using php 7 is a must these days and if we support the latest 7.x versions it will be a plus for those of us who are in love with making their own sites run faster and faster. I doubt anybody will miss the old 5.x versions even if they run on shared host - most CMSes already run on 7.0 and 7.1 and 7.2 is in progress.

Keep the good work up!

**Comment by Traumflug** [comment]
@therampagerado, there is no need ti convince anybody :-)

If you want to help, set Smarty to *3.1.32* in `composer.json`, run a `composer update`, carefully test the shop and tell us about the findings.

**Comment by therampagerado** [comment]
The problem is that you lost me with the second sentence... :D

**Comment by DaoKakao** [comment]
I tried to upgrade smarty an got a plenty of warnings: Parameter 2 to smartyTranslate() expected to be a reference, value given. I wouldn't go further, and rolled back to older smarty version

**Comment by Traumflug** [comment]
Alright. Not exactly thrilling, but I forwarded Smarty to version 3.1.25, to get at least closer to a solution.

3.1.25 doesn't solve the PHP 7.2 compatibility problem, but it passes Travis CI and my own tests (Smarty 3.1.24 didn't). Let this be enough with the thirty bees 1.0.6 release just around the corner.

**Comment by doclucas** [comment]
I was eventually able to install and run the new smarty 3.1.32 without errors on the front-end by changing:
`smartyRegisterFunction($smarty, 'function', 'l', 'smartyTranslate', false);`
to
`smartyRegisterFunction($smarty, 'function', 'l', 'smartyTranslate');`
or
`smartyRegisterFunction($smarty, 'function', 'l', 'smartyTranslate', true);`
in smarty.config.inc.php

I have no idea if this is the right solution as I did not test the functionality to make sure it remains. I am sure false (for lazy) was there for a reason, so please make sure you test the code thoroughly before applying such changes.

**Comment by Dh42** [comment]
We don't need to upgrade smarty in this version, we are just asking for trouble.

**Comment by gonssal** [comment]
This has the potential of breaking compatibility with lots of PrestaShop themes, because PS1.6 is still on 3.1.19.

Also check this: https://github.com/PrestaShop/PrestaShop/pull/3342

As much as we'd all love a faster (potentially 50% faster) and less buggy Smarty version, breaking stuff is not nice.

**Comment by Traumflug** [comment]
> I think we need to fork into a 1.1.x to make this update

Not sure how this would help. Assuming the move to Smarty *3.1.25* breaks something (which it shouldn't), it breaks the same way on *1.1.x*, loosing compatibility with all the themes.

I'd much prefer to identify eventual trouble with *3.1.25* and establish retrocompatibility for these cases. Unlike PS 1.6, we can't stick with *3.1.19* forever. Still we should stay compatible with PS 1.6 themes for the next few years, far beyond the point where we can ignore PHP 7.2 incompatibilities.

Only caveat with all this: I'm not aware of any trouble due to the move, so I can't fix something. My developer shop works just as well as with *3.1.19* :man_shrugging:

**Comment by doclucas** [comment]
You are right.
If I were you, I'd switch to 3.1.32 (not .25), adjust the core to work correctly with the default template (that tip I gave you above can help with that), test a few templates, release a beta build for others to test as well and report any reproducible issue, if they find any, and launch it.
If done right. there is no reason for it not work well with current PS 1.6 templates, as I explained above.

**Comment by Dh42** [comment]
The idea of increasing the subversion number is because it gives us the flexibility of making 1.1.x compliant with php 7.+. We need to starting sun setting 1.0.x and moving on to 1.1.x where we can remove some unmaintained packages (or at least fork them and maintain them). 

But strictly speaking 1.0.x just needs up to 7.1 support. If we keep adding features and support 1.1.x will never come and we will be at 1.0.15 that is frankenstiened together. There is no reason to update to .25 of smarty if we are going to update 1.1.x to the latest. 

As a note, any smarty update is going to break themes and modules, this is something @firstred  and I tested a while back.

**Comment by doclucas** [comment]
> As a note, any smarty update is going to break themes and modules, this is something @firstred and I tested a while back.

Any smarty update **on the same unmodified/unadapted core** is going to break themes and modules, to be exact.

**Comment by doclucas** [comment]
When you eventually reach the point of making TB fully php 7.2 compatible, I highly recommend you run the code through the PHPCS with [PHP Compatibility Checker](https://github.com/PHPCompatibility/PHPCompatibility).
It will help you detect around 90%+ of the issues (the most important ones), although it won't help with issues where `count()` and `sizeof() throw errors or with issues like [this one](https://github.com/PHPCompatibility/PHPCompatibility/issues/560), watching the error log will guide you and the TB users to the other issues that need correction.
Note that, since TB is a fork of PS 1.6 which is not PHP 7.2 compatible, and thus most of its addons (PS 1.6 addons) and themes are not coded for PHP 7.2 compatibility, this will add another challenge to this mission.

**Comment by Traumflug** [comment]
On branch _1.1.x_, Smarty was forwarded to version 3.1.33 and found to work flawlessly with the default theme. Together with all the fixes to silence PHP 7.2 warnings over the recent months I think this issue can considered to be solved.
