### ISSUE TITLE
tbupdater - fileactions merge does not work correctly.

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#619]
Reported on [forum](https://forum.thirtybees.com/topic/2051/release-1-0-7-is-there/51)

Problem:
- file actions for 1.0.6 marks `random_compat` for deletion
- file actions for 1.0.7 marks `random_compat` for addition

When performing update from 1.0.6 to 1.0.7, it works correctly -- `random_compat` package is added. 

When performing update from 1.0.5 or older version, file actions for both versions are incorectly merged -- it results in `random_compat` package removal

**Comment by Traumflug** [comment]
Hmm. Comments like these https://github.com/thirtybees/tbupdater/blob/master/classes/AjaxProcessor.php#L816 do not exactly indicate that a file deleted as well as added ends up being deleted. I'll have to investigate deeper.

**Comment by Traumflug** [comment]
The last six commits, currently on [branch *markus*](https://github.com/thirtybees/tbupdater/commits/markus) should address this, as well as stuff related to _PS_CACHE_ENABLED_ coming up recently.

Resolution of this issue is in this one: https://github.com/thirtybees/tbupdater/commit/dc76d91d0377f1fa98530eb484e222067e6aa791

Comments welcome. If there are no objections I'll make a release with this tomorrow.

**Comment by Traumflug** [comment]
Should be solved with tbupdater release 1.3.4: https://github.com/thirtybees/tbupdater/releases/tag/1.3.4
