### ISSUE TITLE
Pear archive_tar needs to be updated to 1.4.3

### ISSUE THREAD

**Issue by Dh42** [thirtybees/thirtybees#647]
I am unfamilar if this will break anything, but the archive_tar needs to be updated to 1.4.3 to fix a php 7.2 issue.

https://github.com/thirtybees/thirtybees/blob/1.0.x/composer.json#L15

The issue I came across happened on install the blockreassurance module on cpanel / php7.2. The tar would not extract fully and caused the execution to stop before creating the database table. 

Here is the 1.4.3 version fix / update

https://pear.php.net/bugs/bug.php?id=21218

**Comment by Traumflug** [comment]
This entry in *composer.json* should upgrade to *1.4.3* already. Actually I have this version in my development setup.

Does running `composer update` in your setup solve the issue? Running this command once in a while easily gets forgotten in daily business.

**Comment by Dh42** [comment]
I was working on a thirty bees site that started as version 1.0.3 and has over time been upgraded to 1.0.7 I just checked the release and it is using the correct version of the archive_tar, so I am wondering if the updater missed it.

**Comment by Traumflug** [comment]
Looking at the release packages, this PEAR bug is fixed since thirty bees v1.0.2.

Looking at file-action JSONs for updates, none of them marks this file (`/vendor/pear/archive_tar/Archive/Tar.php`) for upgrade. Which is certainly not good. Shops started before v1.0.2 and not doing the manual update for v1.0.4 or v1.0.5 still have the old file.

Looking at file-action JSONs for migrations, it's marked for update in v1.0.1-beta.2, v1.0.6 and v1.0.7. All other migration JSONs are lost, unfortunately.

**Comment by Traumflug** [comment]
This brings up the question why this shop has the old file, while v1.0.3 came with the new one already.

**Comment by Dh42** [comment]
It could have actually been a 1.0.2, I am not sure the whole history of the shop. I think just adding it to the file action list going forward should work.

**Comment by Traumflug** [comment]
Probably a good idea to simply add *all* files to the next update.

That said, one should see this file listed as edited in back office -> *Advanced Parameters* -> *Configuration Information* unless it's up to date.

**Comment by Dh42** [comment]
I concur.

**Comment by Traumflug** [comment]
This issue should be gone with Core Updater. Core Updater does consider all released files.
