### ISSUE TITLE
Disabled module can still be active in back office

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#654]
When I investigated issue reported in this [forum post](https://forum.thirtybees.com/topic/2206/fatal-error-call-to-undefined-method-logger-addlog-in-home-shopboot-domains-boottrailers-nl-public_html-boot-classes-controller-admincontroller-php-on-line-1336) I found out that `displayBackOfficeHeader` is executed even for modules that are disabled. That's very strange. This was deliberately done in commit 92c59b8373383bc70da3cae640ed71e7fdb3bc50. Unfortunately there's no reasons provided.

Maybe this is something that could be addressed in 1.1 version

**Comment by Dh42** [comment]
Specifically so this hook, https://github.com/PrestaShop/gamification/blob/master/gamification.php#L201 would run. 

Notice the module was released like 5 days before that change was made, someone likely put that in so that disabling the module would not disable the functionality. 


This is something that also might affect the GA module as well. https://github.com/thirtybees/ganalytics/blob/master/ganalytics.php#L806

**Comment by Dh42** [comment]
Me either, I was just pointing out likely why it was there.

**Comment by Dh42** [comment]
Is there any downside to rolling this back for the next version? I cannot see one really.
