### ISSUE TITLE
After install language code English = en, should be en-us

### ISSUE THREAD

**Issue by firstred** [thirtybees/ThirtyBees#72]

**Comment by inetbiz** [comment]
While I don't know that much about coding, I was wondering if you might read https://perlgeek.de/en/article/set-up-a-clean-utf8-environment @firstred ? **LANG=en_US.UTF-8** is what I saw there and not sure if the iso code you mentioned in this issue is the same as the operating system's language support?

**Comment by firstred** [comment]
It was just a bug in the original installer. It would take just the `en` part of `en-us`. That was not supposed to happen.

**Comment by inetbiz** [comment]
@firstred was the article link relevant in this case?
