### ISSUE TITLE
1.0.7 breaks TinyMce in multistore

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#784]
I updated on weekend to 1.0.7. It seems to break TinyMce Editor. It's hard to explain, but multishop owner can't really edit product description like that. See here:

https://streamable.com/i0toi

What can be the issue? It seems that actually everything is loaded correctly, but the display doesn't work. It tested it with chrome and firefox...

**Comment by eschiendorfer** [comment]
I think I found the issue: https://github.com/thirtybees/thirtybees/commit/53e659bc2f0bbbf9a9a07d49ec497c9348a69c54

After replacing this file with the old file from 1.0.3, it seems to work again.

**Comment by dosbiner** [comment]
You right, I can confirm this issue. I always use store manager for manage products, so never knew found this issue

**Comment by getdatakick** [comment]
The intent of the original commit was to speed up page loading time by deferring initialization of tinymce editors that are not visible (below the fold). Unfortunately that breaks up bunch of other javascript functions that depends on these objects to exists.

I've reverted this commit. Not sure if it makes sense to invest more effort in re-fixing the original issue. Does anyone feels that the product page is sluggish because of this?

**Comment by Traumflug** [comment]
*At the moment the easiest possible solution [...]*

Hmpf.
