### ISSUE TITLE
Image importing via CSV does not work in 1.0.8 but does in 1.0.7

### ISSUE THREAD

**Issue by Dh42** [thirtybees/thirtybees#884]
I can provide a test file.

**Comment by getdatakick** [comment]
There used to be complicated mechanism to choose the best source image file when generating
product thumbnails. It used list of potential image sources. At the beginning, this list
contained only one file. Whenever new thumbnail was generated, its file was added to this
list of sources.

Commit 5de70ca997e91e0c248a579f4ec04f1b85e2ecbb broke this list generation mechanism, and result
was that no image thumbnails were generated during import.

We could revert this commit, but I don't see any reason why we should have this mechanism at all.
There is best source for resize operation -- source image file. There's no reason to resize
already resized image -- this can only lead to loss of image quality.

This original mechanism *may* be a little bit faster because it uses smaller image sources
for resize operation, but I don't think this benefit is significant enough to justify
image quality loss (and unnecessary complicated php code)
