### ISSUE TITLE
Audit request: don't consider empty translation strings

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#890]
With thirty bees 1.0.8 empty translation strings appeared for some reason. While these strings are pointless and shouldn't happen, their appearance caused quite some disruption, leading to e.g. empty error messages.

One such fix is 5fb6b4acd99b4f454d8cefc94bdd91038877de1b.

Translations are stored in global variables, so auditing all usages of these variables should do the job:
- [x] `$_LANGADM`
- [x] `$_ERRORS`
- [x] `$_FIELDS`
- [x] `$_LANGPDF`
- [x] `$_LANG`

See also issue #879.

**Comment by getdatakick** [comment]
Just a side note from my investigation issue #888: the problem was indeed int the fact that the translations now contains empty strings. These empty strings are already in localization packs downloaded from thirtybees server. 

I don't think there's some *new* code problem in thirtybees core, but there's probably new issue inside localization pack creation script.

Nevertheless, the system should definitely survive empty translations, so this issue is definitely valid and should be addresses.

**Comment by getdatakick** [comment]
All occurrences of global translation arrays has been reviewed and fixed to ignore empty translation strings
