### ISSUE TITLE
Problems with uploading category images

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#895]
Reported here: https://forum.thirtybees.com/topic/2806-category-image-problem/

There seems to be some issues with category image upload mechanism:

> Given the three images that can be specified in a category:
>
> - Category Cover Image
> - Category thumbnail
> - Menu thumbnails
> 
> What I had to do is specify them in order﻿...like this:
> 
> 1. Add the Category Cover Image.
> 2. Save the page.
> (When you go back to the page you will see that the Category Thumbnail image is the same as the Category Cover Image...ignore it.)
> 3. Add the Category Thumbnail.
> 4. Save the page.
> 5. Add/upload the Menu Thumbnail(﻿s)
> 6. Save the page.
> 
> Notes:
> -If you rush the steps﻿, and try to save all at one time, things﻿﻿﻿ won't work right.
> -If you ever change the Category Cover Image, you will have to repeat steps 2 through 4.
> -If you ever regenerate images, you will have to repeat steps 2 through 4.

**Comment by getdatakick** [comment]
Investigation: Category thumbnail

Category thumbnail is generated on the fly and saved into file `_PS_IMG_DIR_/tmp/category_<id>.jpg`. The source file for this thumbnail is Category Cover Image. There is a *hack* in `AdminCategoriesController::postImage` that allows for custom thumbnail image to be loaded. This hack saves custom image as a category medium image (`img/c/<category_id>-medium_default.jpg`)

This is mechanism has many drawbacks:

1) when new Cover Image is uploaded, old thumbnail is dropped. That's because file `img/c/<category_id>-medium_default.jpg` is overwritten with resized cover image
2) when images are regenerated, the image all versions are removed, including `img/c/<category_id>-medium_default.jpg`. This again lead to lost of custom thumbnail

The proper solution would be
1) keep thumbnail source file in some dedicated location (not as a `/img/c/<category_id>-medium_default.jpg`), for example as `/img/c/thumbnail-source-<category_id>.jpg`
2) find all places in the core that calls `ImageManager::thumbnail` for categories and fix it to use this new location as a source

Alternatively, we could drop this custom thumbnail functionality completely.

**Comment by KennyStier61** [comment]
Any update?

**Comment by Bartislartfass** [comment]
Same and worser here...  Use TB 1.1.0 updated from a running PS 1.1.17, using my old and modified default bootstrap template. I also got the problem that my category icons do not appear in the FO. But they are visible in the BO...  

Also I can reproduce the error chain - as in the linked forum post - completely, quote: 
_-The Category Thumbnail does not show at all.  Just a place holder.
-The Category Cover Image shows in place of the Category thumbnail.
-The Category Cover Image shows as the Category Cover Image (as it should)._

"Aggravation" is that I use a "pretty-url" module, but which is officially recommended by the TB-Store.

Since I guessed that it comes from the "pretty url ", I contacted the developer of the module. He had a look at it, but he can't agree that his module is the evil one..

Regenerate thumbnails, rebuild htaccess, check all known Bugfixes - all up to date. ... 
everything already tried unsuccessfully. Meanwhile I asked my freelancer to look for the problem, but he asked me - meanwhile after 1,5 days of debugging - to get in contact with TB.

I can still live without the category icons, but much worse is that in my shop an important "text-customizer" is affected, in which my products can't be colorized anymore! The debugger console also wipes out 404 errors here, just like with the missing category icons. Also i´ve contacted the developer of this module, his Answer: ### There is a 404 error when the module request the colorisation url (....) Do you have a module like pretty url or something like that?

The most important module in the shop doesn't work and not even the contacted developers know how to proceed ... A nightmare! Any help out there?

**Comment by palo** [comment]
> -The Category Thumbnail does not show at all. Just a place holder.
> -The Category Cover Image shows in place of the Category thumbnail.
> -The Category Cover Image shows as the Category Cover Image (as it should).

Also, it's impossible to have category thumbnail without the cover image.
In category.tpl   `$subcategory.id_image` depends on `Category::getSubCategories` finding the cover image.

**Comment by getdatakick** [comment]
Fixed by recent image review rewrite
