### ISSUE TITLE
This is not a valid version

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#915]
While installing the Alabaz Paypal module I got the error "This is not a valid version".

After some research it turned out that this module has its version number set to '16.0.1.4' in paypal.php. It looks like TB has a problem with so many levels. The problem was solved when I changed the version to '16.0.1'.

![exception](https://user-images.githubusercontent.com/13930107/56851699-391c6200-6912-11e9-8217-75c722775126.jpg)

**Comment by Dh42** [comment]
We use semversion, if a developer does not properly know how to version his modules I am not sure what we can do.

**Comment by musicpanda** [comment]
Are you serious that sticking to some obscure doctrine is more important than Prestashop compatibility?

Alabaz sells around a 100 different Prestashop modules. If such a company is not important enough for Thirty Bees to be flexible, who is? It seems to me that then it is doomed to obscurity.

**Comment by Dh42** [comment]
I don't know if I would call something that governs all modern software development and obscure doctrine. This is one module, by one developer, that I have honestly never heard of. I see they have 88 different modules on their site. In the 5000 Prestashop sites I have worked on, I have not come across one on one site. 


That being said I will defer to what @Traumflug  and @getdatakick  think is best. 


As for doomed to obscurity, one monkey does not make the circus. If it takes one monkey to make your circus, you have an all eggs in one basket problem.

**Comment by musicpanda** [comment]
Thirty Bees operates in the Prestashop eco-system. And Prestashop consistently uses four part version numbers (see 1.7.5.1 or 1.6.1.23). It is a bit odd to expect in such an environment that module suppliers use three part version numbers. 

You suggest that the module developers are the victim of this policy. I think it is rather the Thirty Bees users. I wasted a lot of time on this issue and almost spent 50 euro for another module.

If you want "modern software development": what about clear error messages? This error message is absolutely unclear and I spent a long time assuming that somehow the module didn't accept the Prestashop version number in Thirty Bees (1.6.1.999). Only after I started to debug, found the offending version number and did a text search I found the real reason.

**Comment by Traumflug** [comment]
Interesting problem. SemVer as well as PHP's built `version_compare()` shouldn't have an issue with comparing versions of varying length and `1.6.1.999` _is_ a four part version.

Regarding this _"16.0.1.4"_, is it really a _16_ in the front, or is this a typo? If it's a sixteen, it's probably a typo by the module developer and he should have an interest in fixing this him selfs.

If this isn't the issue, could you send me a copy of this file, @musicpanda ? This would help a lot to see what the actual issue is. My email is markus@thirtybees.com.

**Comment by getdatakick** [comment]
I've just tested this on 1.0.8 / 1.0.x and module with version '16.0.1.4' can be installed without any problems. Maybe there were some extra characters in this module's version? (some characters may not be visible in editors, but they are still there)

**Comment by Traumflug** [comment]
I got a copy of the module and can confirm @musicpanda's findings.

Looking at the [SemVer documentation](https://github.com/vierbergenlars/php-semver/blob/2.x/README.md#versions) and [its code](https://github.com/vierbergenlars/php-semver/blob/2.x/src/vierbergenlars/SemVer/expression.php#L7) it indeed supports only versions with up to three parts.

**Comment by Traumflug** [comment]
Commit be2813efa62a9bdce3f42450cc78632e29fa7e1b should fix the issue (works for me). It replaces `SemVer::gt()` with PHP's good old `version_compare()`.

Regarding SemVer its self, see #916.

Thanks for reporting, @musicpanda. If the fix doesn't work for you, please don't hesitate to reopen this issue.

**Comment by getdatakick** [comment]
I was quite confused why this change had to be made, because I didn't have any problems with installing modules with 4-level version on my tb:

<img width="500" alt="install" src="https://user-images.githubusercontent.com/34651851/56882791-f15a1f80-6a64-11e9-80b7-8f759a025921.png">

As it turns out, this problem can occur only for native modules -- modules that are listed in [http://api.thirtybees.com/updates/modules/all.json](api.thirtybees.com/updates/modules/all.json) file.

Obviously, the expectation is that all these modules have valid semver version, as they are maintained by thirtybees team. 

In this case, there must be module name collision, probably paypal.

I think that the fundamental problem here is that tb uses module name as a key.

**Comment by musicpanda** [comment]
The module name was indeed paypal.

**Comment by Traumflug** [comment]
> I think that the fundamental problem here is that tb uses module name as a key.

Assuming module names on disk as being unique should be a fairly safe assumption, as no two modules with the same name can exist in the modules directory. I'd point the finger to the module developer here for naming his module like a (pretty popular) official module. That's asking for trouble.

If this turns out to be a larger problem we could also compare the given module developer before comparing versions to find out whether an update exists or not.

**Comment by getdatakick** [comment]
This is very arguable. It's easy to assign blame to developer because he used `paypal` name for his module. But what do we know? Maybe at the time when he released the module for the first time, there was no official `paypal` module available. Maybe this was prestashop's fault in the first place.

Anyway, the problem really is that the *core* is trying to upgrade module that it should not. Just because there is a module with the same name as some entry in all.json doesn't mean it is the same module. 

Instead of assuming this, core should verify installed module is known. This should be fairly easy, for example by comparing module's fingerprint. If the module on the disk has different fingerprint, then updater should not offer update. And it shouldn't  matter if it's because somebody modified the original module, or because it's entirely different module with the same name. It's not something that's updatable. Period. 

Note that this is recurring problem, I have seen this many times on forum. People often ask about how they could prevent updating of module (because they have custom modification). They worry about some of their employee accidentally hitting *update all* and destroying their changes...

Also, prestashop is using `module_key` property to uniquely identify modules in addons. It looks like [this](https://github.com/getdatakick/pricealert/blob/3046670c229ce8ca10ac3945e8ac07e3d58b4c06/pricealert.php#L24).

**Comment by Traumflug** [comment]
Underlying problem not solved yet.

**Comment by Traumflug** [comment]
What do you think of this? e568021ec8b40240f9d878fb8e580c8420ef662c

**Comment by getdatakick** [comment]
> What do you think of this? [e568021](https://github.com/thirtybees/thirtybees/commit/e568021ec8b40240f9d878fb8e580c8420ef662c)

Great. Even though it's a small code change, it will help a lot

**Comment by Traumflug** [comment]
Thanks for reviewing. Moved to _1.0.x_.

Crossing fingers issues are solved now. If not, no problem to reopen the issue another time :-)
