### ISSUE TITLE
CSV Import Specific prices -- dates are not imported 

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#931]
Copy of https://github.com/thirtybees/thirtybees/issues/372#issue-264394641

As reported on the forum:

https://forum.thirtybees.com/topic/934-934/csv-import-specific-prices-for-a-period

![](https://forum.thirtybees.com/assets/uploads/files/166/1507631425359tb-scpr.png)

Specific price periods are not imported.

Could possibly be a date format mismatch.

**Comment by ksimunovic** [comment]
I was able to reproduce it and see where is the "issue" but I'm not sure if this actually a bug. To me, it looks more like an enhancement, because the import works normally when you use the format specified in the frontend "yyyy-mm-dd".

The lines in question start here in [AdminImportController](https://github.com/thirtybees/thirtybees/blob/1.0.x/controllers/admin/AdminImportController.php#L2924) which validate the date using the method from the [Validate](https://github.com/thirtybees/thirtybees/blob/1.0.x/classes/Validate.php#L735) class.

The question is, should the code in the AdminImportController stay as it is currently and have this marked as the enhancement or should I use the language locality setting and date formats to convert the date from the import file to the database?

**Comment by Traumflug** [comment]
Thinking about this more, it's quite a tricky issue. I could well imagine a UK based merchant (date format YYYY-MM-DD) getting CSVs from an US based supplier (date format YYYY-DD-MM), so neither auto-detection (four digits in the front vs. four digits in the back) nor looking into the shop's preferred date format would work.

Looks like this needs a selector for choosing the date/time format from a list and some usage of [DateTime::createFromFormat](https://www.php.net/manual/en/datetime.createfromformat.php).

**Comment by Traumflug** [comment]
BTW., the original forum post is here: https://forum.thirtybees.com/topic/934-934/csv-import-specific-prices-for-a-period/. It comes with a CSV demonstrating the issue.

**Comment by ksimunovic** [comment]
This could then be solved e.g. adding a new column type "Discount from (custom)" which would, under "Rows to skip" open a new input called "Import date format" according to the [PHP understandable date formats](https://www.php.net/manual/en/datetime.createfromformat.php) and this would be used in createFromFromat().

**Comment by Traumflug** [comment]
Sound good!

Here are my attempts to describe how the engine for creating such widgets works: http://jump-ing.com/traumflugs/using_helper_for_options and http://jump-ing.com/traumflugs/helper_field_select I hope this helps.

**Comment by Traumflug** [comment]
For those watching this issue see #975.

**Comment by Traumflug** [comment]
This should be solved on branch _1.0.x_ as well as on _1.1.x_, thanks to @ksimunovic.

My own tests work just fine. If it doesn't work for you, please don't hesitate to re-open this issue.
