### ISSUE TITLE
Warnings for pdf and mail template translations

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#960]
When you choose under translations for pdf files you get a couple of warning. It looks like in each of those cases the software is trying to run file_get_contents() on a directory. Possibly the filename is empty(?)
![trans1](https://user-images.githubusercontent.com/13930107/58898230-6b339780-86fa-11e9-9745-91d9f03a0715.jpg)

Things are worse under translations for mail templates. You get nonsense warnings that: "An email folder exists for the nl language, but not for the standard language (nl) in ..."
![trans3](https://user-images.githubusercontent.com/13930107/58898489-ff9dfa00-86fa-11e9-93ec-6f0f12ea72ca.jpg)

Separate from this there are warning about missing directories
![trans2](https://user-images.githubusercontent.com/13930107/58898595-31af5c00-86fb-11e9-9dc9-8708d0fef2f5.jpg)

These generate PHP errors too:
![trans4](https://user-images.githubusercontent.com/13930107/58898758-8eab1200-86fb-11e9-874c-e5d4529e409c.jpg)

**Comment by Traumflug** [comment]
Well, do these directories actually exist and are the files readable? As you probably know, AdminTranslationsContoller scans all related source files to find translatable string.

Also, all these paths appear to have a mix of forward and backward slashes as directory separator. Not sure whether this works as expected. A fix would include to make it all forward slashes even on Windows, PHP is said to work fine with all forward slashes.

**Comment by musicpanda** [comment]
Back-and-forward slashes in Windows are not a problem. Windows treats them the same. So don't make anything special for them - it will needlessly complicate the code.

As for the PHP warning for the mail templates, the templates are there.  The problem is the way the subdirectory in which the shop stays is handled. After htdocs you should get "/_snoeptb7/themes". Instead you get "/_snoeptb7//_snoeptb7/themes". 

Some mail templates get a normal error message while others get this raw php error. I haven't explored what is the reason for that.

**Comment by musicpanda** [comment]
I took a little time to investigate the first two points a bit more. Both happen also in Prestashop 1.6.1.23. Prestashop 1.7 does not have a separate entry for pdf translations in its menu.

The second problem can be fixed by changing the function getEmailHTML() file AdminTranslationsController.php. 

One line is changed (in the second condition). It should become (borrowed from PS 1.7):
`    public static function getEmailHTML($email)
    {
        if (defined('_PS_HOST_MODE_') && strpos($email, _PS_MAIL_DIR_) !== false) {
            $email_file = $email;
        } elseif (__PS_BASE_URI__ != '/') {
            $email_file = str_replace(__PS_BASE_URI__, _PS_ROOT_DIR_ . '/', $email);
        } else {
            $email_file = _PS_ROOT_DIR_.$email;
        }

        $email_html = file_get_contents($email_file);

        return $email_html;
    }`

**Comment by ksimunovic** [comment]
@musicpanda I think you were very close and partially correct. The problem lies in that the code tries to open the directory which exists but throws an error anyway. 

The reason is because on Linux and Windows different results are received when you attempt to open a directory with file_get_contents. In this case this is runned:

$content = file_get_contents("/var/www/default/modules/tbupdater/classes/GuzzleHttp");

Which on Linux produces $content = "" (empty string), but on Windows it gives $content = false, and a warning you are seeing. Correct fix, in my opinion, would be to double-check if the $filePath is the file, just like it was done [a few lines before](https://github.com/ksimunovic/thirtybees/blob/85b5fc75a91a0815fb32067619fb0ca5cd8f8e07/controllers/admin/AdminTranslationsController.php#L3365).

Can you please check this if this fixes your warnings?

**Comment by musicpanda** [comment]
This fixes indeed the popup warnings.

Note that the other problem that I mentioned - a lot of problems with the email translations on the translations page - is still there. But that is such a mess that I wonder whether the option shouldn't be removed from the menu as most people will directly edit the files.

**Comment by ksimunovic** [comment]
@musicpanda I investigated this more and I don't believe the problem is in the installation process itself. Process of filling modules with translations happens only once when you install a new language and visit mail translations, [AdminTranslationsController.php#2659](https://github.com/thirtybees/thirtybees/blob/1.0.x/controllers/admin/AdminTranslationsController.php#L2659). So this has been run once, therefore some of the modules have the translations, and then other modules have been added and that's why they don't have the translations. Could this be the case with your installation?

One workaround I found out would be to add a new language e.g. German and without downloading the language pack just go to translating mails for your theme. This will throw errors as there are no German language files but will also copy nl files to all modules which don't have the translations. Afterwards, the German language can be deleted. This worked for me.

Regarding the error messages: they are a bit misleading because they had hardcoded language name in the message so this was also translated. What was also misleading was that directory name was changed before showing it to the user e.g. from "nl" to "en" -> to match the error which is later translated "English language files must exist..", [AdminTranslationsController.php#3072](https://github.com/thirtybees/thirtybees/blob/1.0.x/controllers/admin/AdminTranslationsController.php#L3072). Error messages are now updated to match the error when there are no translations files in the module folder.

**Comment by musicpanda** [comment]
Thank you for fixing the error message.

I beg to disagree on the module mail translations:
 - this happens right out the box. I don't need to add or delete anything.
 - once I understand the problem I can apply some workaround. But in my opinion this should either work out of the box or not be implemented at all.
 - I checked the mail translations in Prestashop 1.6 and found that it has has the same problem. It gives the same missing files in folder errors. However, it doesn't produce the "A mail directory exists for the nl language" type errors at the top of the page.

Below is what I got with a German language test shop (I gave as shop location the Netherlands so that language was automatically installed too). This is a fresh 1.1 test shop without any additions. I get
![trans1](https://user-images.githubusercontent.com/13930107/64860666-1e7f2700-d62e-11e9-8fa9-925f2ca6fc5d.jpg)
When I enter this configuration:
![trans2](https://user-images.githubusercontent.com/13930107/64860667-1e7f2700-d62e-11e9-9c4f-34782bbccc6b.jpg)

**Comment by ksimunovic** [comment]
You're right and I think I got to the bottom of it. Your last message gave crucial information for reproducing this bug. On the install, you choose German as your interface language, and Netherlands as the country of your business. This makes thirtybees install German as default language and Dutch as additional.

Due the nature of the installation process, default language is not set until [install.php#289](https://github.com/thirtybees/thirtybees/blob/1.1.x/install-dev/models/install.php#L289), but this information is required a couple of lines before at [install.php#280](https://github.com/thirtybees/thirtybees/blob/1.1.x/install-dev/models/install.php#L280) because installLanguages method calls Language::downloadAndInstallLanguagePack and finally AdminTranslationsController::checkAndAddMailsFiles, which needs default language set. Without default language, this method will get trigger when you access the translations through backend and then will throw warnings about missing files. To fix this I added this special condition which should be triggered only in case of installation without English language and this should copy all the missing files from English to other languages like German and Dutch in this example so this shouldn't happen with all new installs. Missing files in de and nl are replaced with English ones and ready for translation.

In case you already have a site with this problem then the workaround is not really nice because it removes all previous translations.

**WARNING! ALL TRANSLATIONS WILL BE LOST!!**
1. Install new language by going to Localization -> Languages -> Add new language: English (iso code: en, language code: en-us, has to be enabled)
2 .Update the new language, Localization -> Translations -> Add/Update a language: English (United States)
3. Update the old languages, Localization -> Translations -> Add/Update a language: German and Dutch
4. Remove the previous mail translations folders in themes folder to trigger mail copying, e.g. de and nl: 
		www/themes/niara/mails/de
		www/themes/niara/mails/nl
5. Access mail translations for de or nl, no errors should be shown
6. New language English can be removed/disabled
