### ISSUE TITLE
Thumbnail regeneration doesn't regenerate language images

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#961]
Steps to reproduce:

1. Look up existing images, like
    ```
    find img/l -ls
    ```
2. Back office -> Peferences -> Images, scroll all down, click _Regenerate all thumbnails_. Wait until done.
3. Repeat 1. and notice unchanged file creation dates.

Why is this important? Well, each theme comes with it's own set of image types ( = image sizes), so they need their own set of "language" images. These images are actually placeholders for missing images, images with text like _No image available_ or _Kein Bild verfügbar_.

Alternative would be to drop the concept of per-language placeholder images altogether and always use the language agnostic one. This one:

![grafik](https://user-images.githubusercontent.com/318581/58976277-5a9d2300-87c7-11e9-968f-bba3a59e2be4.png)

P.S.: intitially these placeholder images get generated in _install-dev/models/install.php_, `copyLanguageImages()`.

**Comment by ksimunovic** [comment]
@Traumflug 

The problem here is that this language specific files are not available after initial install because they are located in install_folder/langs. As far as I know, install_folder could be different on almost any installation so there's no way to access this folder post-installation.

Maybe the best solutions would be to stash no picture image used on install somewhere else so it can be re-used for regeneration in theme's sizes.

Other solution could be what you already stated, make them language agnostic and re-generate them when the other images are regenerated. Currently, language images are altogether skipped upon regeneration, only generated on install.

Also interesting, when you add new language with a no picture image, img/l only gets the image flag, it doesn't get all required image sizes by the theme.

What do you think?

**Comment by Traumflug** [comment]
I'd vote for removing these text-images. The language-agnostic camera picture needs no regeneration and works just fine for the intended purpose.

This would allow to remove quite some (broken) code.

**Comment by Traumflug** [comment]
Removing all the related code would be quite some work, see e.g. https://www.prestashop.com/forums/topic/489878-cannot-write-no-picture-image-to-categories-images-folder/

As this is no immediate problem (fallback to the camera picture works) I'll mark this as enhancement.

**Comment by getdatakick** [comment]
Fixed with recent image rewrite
