### ISSUE TITLE
Shopping Cart shows "Free Shipping!" when weight has been exceeded for all available carriers

### ISSUE THREAD

**Issue by techjp** [thirtybees/thirtybees#963]
If you add enough items to the cart that the total combined weight exceeds the maximum weight of all available carriers the cart will show "Free Shipping!" instead of "No Shipping Available":

![image](https://user-images.githubusercontent.com/7457115/59102729-ef3e8700-8967-11e9-8bfa-9dd3596908a5.png)

The same thing will happen on the "Shopping-cart Summary" page, the first page of the checkout process, if additional items are added to the shopping cart to the point that the total combined weight exceeds the maximum weight of all available shipping carriers:

![image](https://user-images.githubusercontent.com/7457115/59102754-054c4780-8968-11e9-8875-495ba0db5f5b.png)

Once the checkout process continues and reaches step 4 the user is finally told that no shipping carrier is available because the maximum weight of all available carriers has been exceeded:

![image](https://user-images.githubusercontent.com/7457115/59102818-2f056e80-8968-11e9-8c3f-6a65696e3c11.png)

When viewing the shopping cart it should not say "Free Shipping!" when in fact there are no carriers available. It should either show nothing at all about shipping or (better) it should say "No Carrier Available", "Shipping Not Available" or a similar message.

The default install of TB does not assign any weights to the sample products so this problem is not easily visible. If any of the devs would like access to my 1.0.8 test server to try this problem for themselves I am happy to provide credentials by PM either here or on the TB forum. (I am dynambee on the TB forums.)

**Comment by techjp** [comment]
Should note that I just installed the Core Updater module and updated everything with the Bleeding Edge option. This issue still exists even after the most recent updates.

For what it's worth this behavior is identical in PS 1.6.1.24, the most recent version as of this comment.

**Comment by techjp** [comment]
More details, tests, results, and discussion [on the TB forums](https://forum.thirtybees.com/topic/3105-shopping-cart-shows-free-shipping-when-weight-has-been-exceeded-for-all-available-carriers/).

**Comment by ksimunovic** [comment]
I managed to reproduce this according to test cases on the forum but only on the Shopping-cart summary screen.

What I've found is that this bug happens as the result of JSON returned from add to cart request. While I was testing upper cart pop-up was updated correctly every time, as seen on screenshots but the page itself had problems. Also, all problems are found 

On the image 1, you can see my test case with the product of weight 0.5kg and a default carrier with max weight 3kg. With qty 6 everything works as it should but with qty 7 shipping info is not removed (and should be because there are no available carriers). This only happened with logged in user because it had a delivery address set so the line which hides the shipping info (in non-logged in users) in [cart-summary.js](https://github.com/thirtybees/community-theme-default/blob/30a27a8976f87917323a90e1bd43933398cd65fb/js/cart-summary.js#L764) is skipped.

Possible solutions are adding something like this in cart-summary.js just under the line [#764](https://github.com/thirtybees/community-theme-default/blob/30a27a8976f87917323a90e1bd43933398cd65fb/js/cart-summary.js#L764):

    if (json.carrier.id == null && !json.free_ship)
        $('.cart_total_delivery').hide(); 

@techjp Does your upper pop-up cart behaves correctly as in the screenshots or does it works differently? I've seen in the forum you mention it isn't working correctly but to me, it seems that you were describing shopping-cart summary page (from yours and my screenshots).

![1](https://user-images.githubusercontent.com/10188612/59624729-d8521e80-9137-11e9-9968-498d481bd45c.png)

![2](https://user-images.githubusercontent.com/10188612/59624735-db4d0f00-9137-11e9-901c-0a406a5c9593.png)


I also noticed one more bug regarding the rendering of the summary table.

If you set the qty out of range, e.g. 7 and refresh the page, everything loads correctly, no shipping info in the summary, but if you then go in acceptable range qty <= 6 then the table layout breaks down in the last row and "Total shipping" label is wrong, doesn't say is it tax inc. or excl. 

![3](https://user-images.githubusercontent.com/10188612/59624738-de47ff80-9137-11e9-9db3-91f570afabf6.png)

**Comment by techjp** [comment]
> Does your upper pop-up cart behaves correctly as in the screenshots or does it works differently? I've seen in the forum you mention it isn't working correctly but to me, it seems that you were describing shopping-cart summary page (from yours and my screenshots).

I had problems in both places but now can only reproduce them in the summary page. What I described towards the end of the TB forum thread (and what you described in your detailed post here) is what I experience with the cart now.

**Comment by Traumflug** [comment]
Thanks for the work, @ksimunovic https://github.com/thirtybees/community-theme-default/pull/75. Nice work, but for my taste this solution (just removing the message) appears to be a bit cheap.

At least we'd need a label 'No shipping available'. Better would be a label giving the reason as well: "No shipping, product selection too heavy", "No shipping, selected product values too high", "No shipping, product selection too large", depending on the reason. Not sure how many code changes this needs.

And looking at these checkout page screenshots above, I see a whole bunch of additional issues:
- As you said, rendering can collapse. Probably some JavaScript glitch, AFAIK rendering gets adjusted by JS after small changes, but the initial page gets rendered in Smarty. Yes, kind of duplicate code.
- The shipping row vanishes on unavailable shipping, rather than stating unavailable shipping (ideally with reason, like above). This way customers are expected to switch back and forth between shipping and summary page until it fits ... which they likely won't do, abandoning the order.
- Warning text in the yellow box repeats multiple times, apparently due to many carriers being available.
- First sentence in the yellow box is of unknown origin. Shouldn't be there.
- Red box does it much better, but is, of course, a duplication. Can this yellow box simply get removed without loosing information?

Also please be aware that there are multiple types of checkout pages. Standard, OPC (One Page Checkout) and advanced. They have similar, but not identical templates. OPC can get turned on and off in back office -> Preferences -> Orders: _Order process type_. I forgot what 'advanced' is, but changes to one template should get forwarded to the other two/three, if applicable.

And sorry for the mess, such entire stacks of issues are probably the result of a software receiving issue-oriented patches over many years.

**Comment by Dh42** [comment]
I am not sure how that will work. Like say I live in the EU and I come to the site as a not logged in user. The max shipping weight to the EU is 50kg, but the max shipping weight to the US is 100kg. What should it show when I have 75kg in my cart?

**Comment by Traumflug** [comment]
Not logged in means the US carrier is considered, so it shows an available carrier. This carrier vanishes as the user logs in with an EU shipping address.

As far as I can see, this logic needs no change. All of the above is only about displaying messages in various places.

**Comment by Dh42** [comment]
I am not sure that would work. What about carriers that get live rates? There is no stored area that shows knows if a shipment can be made with out having the api contacted. Like SUPS, FEDEX, UPS, DHL.

**Comment by Traumflug** [comment]
You're totally right, there are many challenges with finding the right shipping fee. As said, the logic for finding this fee is not going to be changed. At least not in this issue.

**Comment by Traumflug** [comment]
I mean, if you think about not showing shipping fees at all, that's not an option here in the EU. Law demands at least a hint to them right next to the article price (often solved with a link to a CMS page describing them) and a stated price before the customer can send the order. Which means, it has to be shown on the checkout page.

**Comment by ksimunovic** [comment]
Sorry for the late intervention. @Traumflug here's a solution which should cover all the points you mentioned here:

> And looking at these checkout page screenshots above, I see a whole bunch of additional issues:
> 
> * As you said, rendering can collapse. Probably some JavaScript glitch, AFAIK rendering gets adjusted by JS after small changes, but the initial page gets rendered in Smarty. Yes, kind of duplicate code.
> * The shipping row vanishes on unavailable shipping, rather than stating unavailable shipping (ideally with reason, like above). This way customers are expected to switch back and forth between shipping and summary page until it fits ... which they likely won't do, abandoning the order.
> * Warning text in the yellow box repeats multiple times, apparently due to many carriers being available.
> * First sentence in the yellow box is of unknown origin. Shouldn't be there.
> * Red box does it much better, but is, of course, a duplication. Can this yellow box simply get removed without losing information?

I added a new row now which will be populated with ajax and show the appropriate error message why the shipping is not possible. It is different than the one the page load because this was already built-in it was just not working properly. Built-in error mechanism was overwritten in [FrontController.php#974](https://github.com/thirtybees/thirtybees/blob/1.1.x/classes/controller/FrontController.php#L974) because of $this->errors wasn't set, which then made it overwritten in smarty variables.

Extra yellow box of unknown origin was due to the wrong array initialization in smarty which created an array containing one element, an empty string, which was then interpreted by smarty as null or 0 and that's why it showed an extra "The product selection cannot be delivered by the available carrier(s). Please amend your cart.".

Inspecting the code I found out red box is used exclusively for standard checkout and that's why I restricted yellow box only to the one-page checkout.

Changes made in Cart.php are copied from OrderController:processAddress() so the error messages are matching. Code is adjusted so the errors which are returned from functions are kept and passed to frontend.

To add to the discussion regarding the logic, the logic for the errors itself is not changed, they are now only better propagated to the frontend and shown to the user.

**Comment by Traumflug** [comment]
@ksimunovic, looks like you made your way through the chaos. Excellent.

Adjusted commit messages, duplicated theme commit to the other theme, slightly simplified controller code (`getSummaryDetails()` guarantees to return an array, merging an empty array is fine), nothing essential. Thank you very much!

@techjp, bleeding edge branch _issue-963_ should be available in Core Updater in a couple of minutes, I'd be happy to read your evaluation.

**Comment by Traumflug** [comment]
Moved to _1.1.x_.
